name: facebook/redex/nightly
on:
  schedule:
  - cron: 0 0 * * *
#   # 'filters' was not transformed because there is no suitable equivalent in GitHub Actions
env:
  CACHE_VERSION: xxxxx1
jobs:
  build-20_04:
    runs-on: ubuntu-latest
    container:
      image: buildpack-deps:focal
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: "./.github/actions/build_debian"
      with:
        job_name: ubuntu_20.04
  build-22_04:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: "./.github/actions/build_debian"
      with:
        job_name: ubuntu_22.04
  build-deb_oldoldstable:
    runs-on: ubuntu-latest
    container:
      image: buildpack-deps:oldoldstable-scm
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: "./.github/actions/build_debian"
      with:
        use_sdk: false
        job_name: debian_10
  build-deb_stable:
    runs-on: ubuntu-latest
    container:
      image: buildpack-deps:stable-scm
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: "./.github/actions/build_debian"
      with:
        job_name: debian_12
  build-deb_stable-w-clang:
    runs-on: ubuntu-latest
    container:
      image: buildpack-deps:stable-scm
    env:
      CC: clang
      CXX: clang++
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: "./.github/actions/build_debian"
      with:
        install_clang: true
        job_name: debian_12_clang
  build-deb_stable-32:
    runs-on: ubuntu-latest
    container:
      image: buildpack-deps:stable-scm
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: "./.github/actions/build_debian"
      with:
        mode_32: true
        job_name: debian_12_32
  build-deb_unstable:
    runs-on: ubuntu-latest
    container:
      image: buildpack-deps:unstable-scm
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: "./.github/actions/build_debian"
      with:
        job_name: debian_unstable
  build-windows-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: "./.github/actions/setup-build-and-test-windows"
    - name: Copy package for CircleCI
      run: mkdir artifacts && mv build/Redex*.zip artifacts/
      shell: c:/tools/msys64/msys2_shell.cmd -defterm -no-start -mingw64 -full-path -here -c
    - uses: actions/upload-artifact@v4.0.0
      with:
        path: ".\\artifacts"
  build-deb_stable-w-clang-llvm-org:
    runs-on: ubuntu-latest
    container:
      image: buildpack-deps:stable-scm
    env:
      CC: clang
      CXX: clang++
    strategy:
      matrix:
        clang_version:
        - 0
        - 15
        - 17
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: "./.github/actions/build_debian"
      with:
        install_clang_llvm_org: "${{ matrix.clang_version }}"
        job_name: debian_12_clang_upstream
